### ISSUE TITLE
bug in the calculation of estimated number of positive tested people that share diagnosis keys?

### ISSUE THREAD

**Issue by pozoo** [micb25/dka#17]
There seem to be a bug in the calculation of estimated number of positive tested people that share diagnosis keys. This number did rise by almost 30% on 24-09-2020 and 25-ß0-2020 while the number of keys transmitted via the CWA on those days stayed almost constant. I cannot imagine this is real. Can you check this?

**Comment by micb25** [comment]
Thank you for reporting this issue. It seems like there have been a lot of users with an invalid TRL profile within the last few days for whatever reason. This also happened in the past, however, with much less impact on the estimated numbers. Thus, I did not subtract these users. I decided now to exclude the 'invalid users' now in the 'users per day sharing their diagnosis keys' and thus, all related data and correlations also have changed now. Unfortunately, this altered slightly the overall number of estimated users in the past.

Since we have [official data](https://www.coronawarn.app/assets/documents/2020-09-23-cwa-daten-fakten.pdf) yet, I opened an [issue](https://github.com/corona-warn-app/cwa-website/issues/391) asking for an official dashboard with the accurate official data. Unfortunately, this data is just compiled in a PDF with some low-quality graphics. Nevertheless, the correlation with the two marked peaks (`2020-09-17`: 205 users; `2020-09-21`: 164) is quiet good reproduced now by the daily package analysis (`2020-09-17`: 203 users; `2020-09-21`: 161). Unfortunately, the number of users with an invalid TRL profile started to increase just after the release of the PDF. I hope to see more official accurate data in the future.

**Comment by vaubaehn** [comment]
Hi @micb25 ,

> It seems like there have been a lot of users with an invalid TRL profile within the last few days for whatever reason.

> Unfortunately, the number of users with an invalid TRL profile started to increase just after the release of the PDF.

do you think that this may be an issue that should be filed to CWA devs? Unfortunately this subject is out of my scope, so I can't support you by taking over.
