### ISSUE TITLE
Question on number of reported keys (23.June)

### ISSUE THREAD

**Issue by ndegendogo** [micb25/dka#19]
I have a question on your diagram of daily reported keys to corona warning app (plot_keys).
Your very first number on 23.June is 477 keys, but I received 503 keys on 24.June. All your other numbers match exactly with what I received.
Do you have an idea how to explain this difference on the first day? Could these be keys from the first week?

**Comment by micb25** [comment]
Yes, I know why this happened. There have been some keys deleted in these packages after they have been published the first time, mainly these which are older than 14 days beginning from the date of download (my hourly ZIP were downloaded on 2020-07-03). As a consequence, I didn't download the very first hourly packages containing all the 503 keys. 

In the beginning, I used the daily packages for the statistical analysis. However, I switched to the hourly packages to have more accurate estimates due to a padding multiplier change during one day and I expected more to come.

**Comment by ndegendogo** [comment]
Thanks!
